owner: gnc178
repo: congenial-couscous
skipDeleteIssues: true

sites:
  - name: API
    url: https://api.callibri.ru
  - name: Landing
    url: https://callibri.ru
  - name: Cabinet
    url: https://in.callibri.ru
  - name: Sync
    url: https://externalcrm.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Skvan
    url: https://skvan.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Gudok
    url: https://gudok.tel
  - name: PopUp
    url: https://catchers.callibri.ru
  - name: Mapi
    url: https://mapi.callibri.ru
  - name: Chapi
    url: http://chapi.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Module
    url: https://module.callibri.ru
  - name: Blog
    url: https://blog.callibri.ru
  - name: Minimo
    url: https://minimo.callibri.ru
  - name: Ws
    url: https://ws.callibri.ru/
  - name: PWA
    url: https://dialog.callibri.ru
  - name: Pong
    url: https://pong.callibri.ru

status-website:
  baseUrl: /congenial-couscous
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Callibri
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
