owner: gnc178
repo: congenial-couscous

sites:
  - name: API
    url: https://api.callibri.ru
  - name: Landing
    url: https://callibri.ru
  - name: Cabinet
    url: https://in.callibri.ru
  - name: Sync
    url: https://externalcrm.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Skvan
    url: https://skvan.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  baseUrl: /congenial-couscous
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Callibri
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
