owner: gnc178
repo: congenial-couscous
skipDeleteIssues: true

sites:
  - name: API
    url: https://api.callibri.ru
  - name: Landing
    url: https://callibri.ru
  - name: Cabinet
    url: https://in.callibri.ru
  - name: Sync
    url: https://externalcrm.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Skvan
    url: https://skvan.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Gudok Landing
    url: https://gudok.tel
  - name: Gudok Cabinet
    url: https://in.gudok.tel
  - name: PopUp
    url: https://catchers.callibri.ru
  - name: Mapi
    url: https://mapi.callibri.ru
  - name: Chapi
    url: http://chapi.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Module
    url: https://module.callibri.ru
  - name: Blog
    url: https://blog.callibri.ru
  - name: Minimo
    url: https://minimo.callibri.ru
  - name: Ws
    url: https://ws.callibri.ru/
  - name: PWA
    url: https://dialog.callibri.ru
  - name: Pong
    url: https://pong.callibri.ru
  - name: Registry
    url: https://registry.callibri.ru
  - name: 2g.tel
    url: https://2g.tel
  - name: Brief
    url: https://brief-media.ru
  - name: SmartSms
    url: https://smartsms.callibri.ru
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Callibri GCDN Script
    url: https://gcdn.callibri.ru/callibri.js
  - name: Callibri CDN Script
    url: https://cdn.callibri.ru/callibri.js
  - name: Gudok GCDN Script
    url: https://gcdn.gudok.tel/script.js
  - name: Gudok CDN Script
    url: https://mod.gudok.tel/script.js

status-website:
  baseUrl: /congenial-couscous
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Callibri
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
